"""
Mechanically ports the locally-tested GenVM v0.2.11 contract to Studio
Next's v0.3.0 conventions. Only import / decorator / base-class / message
spellings change - the same five substitutions already used for this
account's SolvencyOracle, QuoteKeeper, AuditScope, Covenant Sentinel v2 and EntityStanding
ports. Fails loudly if any expected pattern is missing, so a port can
never silently skip a step.

Usage: python3 scripts/port_to_studio_next.py contracts/<name>.py
       -> writes contracts/<name>_studio_next.py
"""

import pathlib
import re
import sys

BRADBURY_HEADER = (
    "# v0.1.0\n"
    '# { "Depends": "py-genlayer:1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }\n'
)
STUDIO_NEXT_HEADER = (
    "# v0.3.0\n"
    '# { "Depends": "py-genlayer:5jycge4q8k23462jtb0b9fyey1s9qz928sz2nbrd9mg4sxqg2qng" }\n'
)


def port(src: pathlib.Path) -> str:
    text = src.read_text()

    def sub(old: str, new: str, count_expected=None) -> None:
        nonlocal text
        n = text.count(old)
        assert n >= 1, f"expected pattern missing: {old!r}"
        if count_expected is not None:
            assert n == count_expected, f"{old!r}: expected {count_expected}, found {n}"
        text = text.replace(old, new)

    sub(BRADBURY_HEADER, STUDIO_NEXT_HEADER, 1)
    sub("from genlayer import *\n",
        "import genlayer as gl\n"
        "from genlayer.types import *\n"
        "from genlayer.storage import TreeMap, DynArray\n"
        "from dataclasses import dataclass\n", 1)
    sub("gl.message_raw['datetime']", "gl.message.datetime")
    sub("@allow_storage\n", "@gl.storage.allow\n@dataclass\n")
    sub("(gl.Contract):", "(gl.contract.Contract):", 1)
    # Consumer contracts only: the cross-contract accessor was renamed
    # (found and fixed live on QuoteKeeper's RetainerConsumer port).
    text = text.replace("gl.get_contract_at(", "gl.contract.get_at(")

    # The header comment describing which file is which.
    text = re.sub(
        r"# (?:This file uses )?GenVM v0\.2\.11 conventions.*?# Header must end in a blank line \(real GenVM v0\.2\.11 requirement\)\.\n",
        "# Studio Next port of contracts/" + src.name + " (the locally-tested,\n"
        "# GenVM v0.2.11 source of truth), generated by scripts/port_to_studio_next.py.\n"
        "# Only GenVM import / decorator / base-class / message spellings differ.\n"
        "# Validated live on Studio Next (genlayer-test's Direct Mode does not\n"
        "# support this generation) - see CONTRACT.md.\n"
        "# Header must end in a blank line (real GenVM requirement).\n",
        text,
        count=1,
        flags=re.S,
    )
    assert "Studio Next port of contracts/" in text, "header comment block not found"
    assert "allow_storage" not in text and "message_raw" not in text and "from genlayer import *" not in text
    assert "get_contract_at" not in text
    return text


if __name__ == "__main__":
    src = pathlib.Path(sys.argv[1])
    out = src.with_name(src.stem + "_studio_next.py")
    out.write_text(port(src))
    print(f"wrote {out}")
